### PR TITLE
add support for Promise.finally

### PR DESCRIPTION
**Pull request by devNimi**

### CODE REVIEW

**Comment by devNimi** [comment]
@fluffynuts
I just felt that we also need to support `.finally`
 can I start working on it,? 
writing specs and other things

**Comment by fluffynuts** [comment]
Sure, go for it.

**Comment by fluffynuts** [comment]
*facepalm* I initially didn't read this as a pull request - thought it was an issue (viewed on FastHub). My bad. 

I'll accept if you add two tests, confirming the behavior that MDN specifies, ie 
1. The function passed to `finally` should be called after the promise has resolved
2. The function passed to `finally` should be called after the promise is rejected. 

Since the current patch simply calls into `then`, I'm not convinced that it will pass both of those tests right now - I'd have to see it to believe it. 

Pull requests to this project must _always_ be accompanied by tests which prove their validity. A solid test suite is what allowed me to completely rewrite this for version 2 when the original architecture would not allow me to fix a bug brought up by a user.

**Comment by devNimi** [comment]
sure, I'm was gonna write specs anyway :)
I just wanted you confirm the development, which you did :)
Thanks 
I'll submit specs soon

**Comment by fluffynuts** [comment]
Please have a look at #13

**Comment by fluffynuts** [comment]
#13 resolves this; closing out.

**Pull request closed without merging**
