### PR TITLE
refactoring: Simplify calling next/catch

### PR DESCRIPTION
**Pull request by ifraixedes**
Simplify the logic of calling the next promise chain.

I didn't remember to do this last refactoring yesterday before I sent the PR #2

### CODE REVIEW

**Comment by fluffynuts** [comment]
I like where you're going with this, but I'd like to suggest a further refactoring on _applyNext:
```
  _applyNext: function () {
    if (this._next.length === 0 || this._paused) {
      return this;
    }

    var next = this._findNext();
    if (!next) {
      return this;
    }
    return this._applyNextHandler(next);
  },
  _applyNextHandler: function (handler) {
    try {
      var data = handler.apply(null, this._data);

      if (looksLikePromise(data)) {
        this._handleNestedPromise(data);
        return this;
      }

      this._setResolved();
      this._data = [data];
      return this._applyNext();
    } catch (e) {
      this._setRejected();
      this._data = [e];
      return this._applyNext();
    }
  },
  _findNext: function () {
    var handler = {
      "resolved": this._findFirstResolutionHandler,
      "rejected": this._findFirstRejectionHandler
    }[this.status];
    return handler ? handler.apply(this) : undefined;
  }
```

Mainly because _applyNext is getting a little long (largely my fault), but also because I try to avoid the switch statement as far as possible, simply because it welcomes code additions and growing, unrefactored code. I've been meaning to write a blog post about this (so I can't link you to it, since it's not written yet), but basically I never see the need for a switch statement:
- If there's only one `case`, then you could use `if`
- If there are two `case`s, then you could use `if / else`
- If there are more, then a strategy pattern, like above, encourages refactoring code to one method per branch, which is more maintainable -- and you don't have to worry about fall-through (which, generally, you don't want).

In the case above, there are technically three scenarios: 'rejected', 'resolved', 'pending' -- so we have three `case`s and you've used the default to handle `pending` -- which is a rational choice. I'd prefer to go with a strategy pattern though, for the the reasons outlined above, even though this should never, ever go beyond three possibilities (: Hope I'm not coming across as too pedantic -- I've also just been having a discussion with co-workers about this; most agree but there's that one particularly stubborn one... Anyways, if you don't mind implementing the above, I'll gladly accept the PR & re-release.

**Comment by ifraixedes** [comment]
Thanks for considering.

Because the refactoring doesn't change any behavior of the implementation (feature, fix bug, etc.), I believe that if you want to refactor it in order to make the next contribution easier according your code style, as maintainer you should do it.

**Comment by fluffynuts** [comment]
Fair enough. I just wanted the PR from you because you did all the initial work and deserve the credit (: I'll merge in my refactor of your refactor soon-ish.
I didn't mean to offend or anything like that -- as I say, I'd have liked the refactor to have been reflected against the person who actually did most of the work, since that's just fair credit. It's how I treat other PRs for similar reasons on other projects (:

**Comment by fluffynuts** [comment]
Fair enough. I just wanted the PR from you because you did all the initial work and deserve the credit (: I'll merge in my refactor of your refactor soon-ish.
I didn't mean to offend or anything like that -- as I say, I'd have liked the refactor to have been reflected against the person who actually did most of the work, since that's just fair credit. It's how I treat other PRs for similar reasons on other projects (:

**Comment by ifraixedes** [comment]
It's fine, no offense, the important part was the PR #2 this one was matter of a minor change; I didn't want to invest my time on your code styling just because of refactoring without providing anything from the external consumer point of view.

Your work in this library is appreciated because it contributes to the open source community, hence I thank you for that.

**Pull request closed without merging**
